{% set name = "make-it-sync" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/make_it_sync-{{ version }}.tar.gz
  sha256: 2b19630e6e6ad7d87aa32a6120113cb61b88872afc88838b98d1d0dc3eebf8b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7

test:
  imports:
    - make_it_sync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gordonwatts/make-it-sync
  summary: Create a sync version of an async function
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gordonwatts
    - matthewfeickert
